@param String version

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="version" content="${version}">
    <title>Harrel.dev</title>
    <link rel="favicon" href="/static/favicon.ico"/>
    <link rel="stylesheet" href="/static/spectre.min.css"/>
    <link rel="stylesheet" href="/static/style.css">
</head>
<body>
<div id="root"></div>
<script src="/static/bundle.js"></script>
</body>
</html>