name: build

on:
  push:
    branches: [ master ]

jobs:
  build-gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 19

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: |
            build/
            Dockerfile
  build-docker:
    runs-on: ubuntu-latest
    needs: build-gradle
    steps:
      - name: Setup tag name
        run: echo "TAG_NAME=${GITHUB_REF_NAME}-$(date +"%Y%m%d-%H%M%S")" >> ${GITHUB_ENV}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_HOST }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Download build output
        uses: actions/download-artifact@v3
        with:
          name: build-output

      - name: xxx
        run: echo "$TAG_NAME"
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY_HOST }}/harrel-site:${{ env.TAG_NAME }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - run: echo "${{ env.TAG_NAME }}"