name: build

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build-gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 23

      - name: Setup Bun.sh
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Execute Gradle build
        run: ./gradlew build --no-daemon

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            build/
            Dockerfile
  build-docker:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    needs:
      - build-gradle
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN  }}

      - name: Download build output
        uses: actions/download-artifact@v4
        with:
          name: build-output

      - name: Set BUILD_VERSION
        run: echo "BUILD_VERSION=${GITHUB_REF_NAME}-$(date +"%Y%m%d-%H%M%S")" >> "$GITHUB_ENV"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            BUILD_VERSION=${{ env.BUILD_VERSION }}
          tags: |
            ghcr.io/harrel56/harrel-dev:${{ env.BUILD_VERSION }}
            ghcr.io/harrel56/harrel-dev:latest

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-docker
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker compose -f /home/harrel/apps/docker-compose.yml down harrel-dev
            sudo docker compose -f /home/harrel/apps/docker-compose.yml pull harrel-dev
            sudo docker compose -f /home/harrel/apps/docker-compose.yml up harrel-dev -d