name: build

on:
  push:
    branches: [ master ]

jobs:
  build-gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 19

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19.7.0

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: |
            build/
            Dockerfile
  build-docker:
    runs-on: ubuntu-latest
    needs: build-gradle
    steps:
      - name: Setup tag name
        run: |
          export TAG_NAME=${GITHUB_REF_NAME}-$(date +"%Y%m%d-%H%M%S")
          echo "${TAG_NAME}" > tag-file
          echo "TAG_NAME=${TAG_NAME}" >> ${GITHUB_ENV}

      - name: Upload tag name
        uses: actions/upload-artifact@v3
        with:
          name: tag-file
          path: tag-file

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_HOST }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Download build output
        uses: actions/download-artifact@v3
        with:
          name: build-output

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY_HOST }}/harrel-site:${{ env.TAG_NAME }}

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/harrel/harrel-site
            sudo ./deploy.sh ${{ env.TAG_NAME }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - name: Download tag name
        uses: actions/download-artifact@v3
        with:
          name: tag-file

      - name: Setup tag name
        run: echo "TAG_NAME=$(cat tag-file)" >> ${GITHUB_ENV}

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/harrel/harrel-site
            sudo ./deploy.sh ${{ env.TAG_NAME }}